services:
  backend:
    build:
      context: ./Backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080